spring.application.name=microservicio-auditoria
server.port = 8011
#server.port=8031

spring.profiles.active=test
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.showsql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=miclavesecretamiclavesecretamiclave
